### ISSUE TITLE
Multiple request can be sent in the single page

### ISSUE THREAD

**Issue by AeroChangmin** [SNUArduinoLabs/coe_control_center#4]
For example, if I click 'Create Content schedule' button multiple times, multiple schedules are created, but not the same number of clicks

**Comment by zeronone** [comment]
I am sorry. I couldn't understand you well. What happens when you click `Create content schedule`

**Comment by AeroChangmin** [comment]
In <code> Add Content (Image/Video) </code> page, when I click <code>Create content schedule</code> the browser status turns connecting. But, at that time I can press same button multiple times, and it create multiple contents.

**Comment by zeronone** [comment]
Yes the web server is based on the request-response model. It would not be
ideal to press the button several times, as it would transfer the data
several times to the webserver. The click counts will not match, because
the browser will cut some of the requests as soon as the new page is
rendered. So please click the button once and wait till the schedule page
appears.
